# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flotilla.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flotilla.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66lotilla.proto\x12\x08\x66lotilla\"\r\n\x0bHintRequest\"\x1d\n\x0cHintResponse\x12\r\n\x05share\x18\x01 \x01(\x0c\"\x1e\n\rAnswerRequest\x12\r\n\x05query\x18\x01 \x01(\x0c\"\x1f\n\x0e\x41nswerResponse\x12\r\n\x05share\x18\x01 \x01(\x0c\x32\x87\x01\n\rWorkerService\x12\x37\n\x04Hint\x12\x15.flotilla.HintRequest\x1a\x16.flotilla.HintResponse\"\x00\x12=\n\x06\x41nswer\x12\x17.flotilla.AnswerRequest\x1a\x18.flotilla.AnswerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flotilla_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HINTREQUEST']._serialized_start=28
  _globals['_HINTREQUEST']._serialized_end=41
  _globals['_HINTRESPONSE']._serialized_start=43
  _globals['_HINTRESPONSE']._serialized_end=72
  _globals['_ANSWERREQUEST']._serialized_start=74
  _globals['_ANSWERREQUEST']._serialized_end=104
  _globals['_ANSWERRESPONSE']._serialized_start=106
  _globals['_ANSWERRESPONSE']._serialized_end=137
  _globals['_WORKERSERVICE']._serialized_start=140
  _globals['_WORKERSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
